### ISSUE TITLE
Create demo URL

### ISSUE THREAD

**Issue by luisherranz** [annabranco/three-bunnies#2]
It'd be amazing to add a demo url to the README so people can see it in action right away.

It's super simple and free with Now:
https://docs.frontity.org/installation-and-deploy/deploy-on-now

If you want, you can create an account on Now and do it yourself. If not, don't worry, let me know and I will deploy it for you :)

**Comment by annabranco** [comment]
That's a great suggestion. I'l go for it. 
Thank you very much! 😊

**Comment by annabranco** [comment]
Demo created here:
https://three-bunnies.annabranco.now.sh/

Great contribution! 😉

**Comment by luisherranz** [comment]
Awesome! 😊✌️
